### ISSUE TITLE
Force closed on Android 11

### ISSUE THREAD

**Issue by kri164** [io7m-com/exfilac#20]
Hello,

I've encountered an error = force closed on Android 11.
Motorola and Xiaomi phones.
On Android 14 it works fine.

**Comment by io7m** [comment]
Hello!

Could you elaborate a bit? Where are you seeing this error? I've never heard of a "force closed" error.

It might be worth trying the `1.1.0` version that'll be out in a few days.

**Comment by io7m** [comment]
Ah, I see this refers to an "application not responding" error (where the dialog offers to force the app to close).

**Comment by io7m** [comment]
Is this, by any chance, happening on the initial loading screen?

If so, I think I've just managed to reproduce it on an Android 9 Xiaomi phone.

**Comment by kri164** [comment]
Yes.
I click on icon, screen flash for milisecond, nothing happened and system dialog informs about non response.

11. října 2024 11:43:02 UTC, Mark Raynsford ***@***.***> napsal:

**Comment by io7m** [comment]
Thanks. This definitely needs to be fixed for `1.1.0`. I'm not yet sure what the underlying cause is.

**Comment by io7m** [comment]
This was due to the database access layer using a standard JDK method that doesn't exist on versions of Android that old. I've tested this on a Xiaomi Android 9 device and the app starts up properly now.
