### ISSUE TITLE
Remote content hash is always null when using Minio

### ISSUE THREAD

**Issue by floryst** [io7m-com/exfilac#34]
## Overview

When using Exfilac with a Minio server, unnecessary upload detection always fails because the remote content has is always `null`, even when the asset already exists on the remote and has not changed.

## Details

Minio stores metadata header names capitalized, i.e. as `X-Amz-Meta-Exfilac-Sha256`. In contrast, I think AWS S3 stores these header names lowercased. As such, [accessing the metadata](https://github.com/io7m-com/exfilac/blob/dc60a51ba7628d400bceb1d256e1da78a5cd2ec2/com.io7m.exfilac.s3_uploader.amazon/src/main/java/com/io7m/exfilac/s3_uploader/amazon/EFS3AMZUpload.kt#L240-L241) from a Minio server returns a `Map<string, string>` containing `{"Exfilac-Sha256": "..."}` rather than the expected `{"exfilac-sha256": "..."}`.

I think the easiest resolution would be to wrap `response.metadata()` in a case-insensitive map, as I cannot configure Minio to return lowercased header names.

**Comment by io7m** [comment]
That's strange. I use `minio` locally as my main storage and I'm not seeing the same problem.

It would be easy to add a workaround for this, but I'd like to track down the actual underlying problem. 

Is there something sitting between you and `minio` like a reverse proxy, perhaps? I use `nginx` for TLS termination between my device and `minio`. I wonder if, by doing that, I'm inadvertently working around this problem and haven't seen it. :thinking:

**Comment by floryst** [comment]
I'm using caddy v2 for TLS termination. Since minio is working in your setup, I'll do some investigation with my setup and get back to you.

**Comment by floryst** [comment]
Turns out caddy uppercases HTTP headers, rather than minio storing headers as capitalized. I set up nginx and caddy in front of a test minio instance, and wrote a header named `x-amz-meta-sha256` through the nginx endpoint. While I didn't test this, I'd wager that caddy would rewrite headers to be capitalized when issuing a PUT through the caddy endpoint.

```
# 8881 is caddy
$ curl -IHEAD http://localhost:8881/hello/pasted.png
...
X-Amz-Meta-Sha256: asdf

# 8882 is nginx
$ curl -IHEAD http://localhost:8882/hello/pasted.png
x-amz-meta-sha256: asdf
```

I would have assumed that the AWS S3 SDKs would use case-insensitive maps for HTTP headers (or at least normalize), but I suppose that is not the case.

**Comment by io7m** [comment]
Thanks for tracking it down.

I agree that the app should work regardless of the header case. I'll add something in to ensure that it's not sensitive to case. :hourglass:
