### ISSUE TITLE
 Unsupported header x-amz-checksum-sha256 error for uploads

### ISSUE THREAD

**Issue by bfgoh** [io7m-com/exfilac#35]
The provider that I am using is Backblaze B2. However, it has errors when uploading a portion of file. It says in the log  Unsupported header x-amz-checksum-sha256

**Comment by io7m** [comment]
It seems that this is documented as unsupported in B2:

https://www.backblaze.com/docs/cloud-storage-s3-compatible-api

Exfilac currently uses them here:

https://github.com/io7m-com/exfilac/blob/83fdc6a1ebd0c4191d70a6e8ffa9e2f127ad45cc/com.io7m.exfilac.s3_uploader.amazon/src/main/java/com/io7m/exfilac/s3_uploader/amazon/EFS3AMZUpload.kt#L216

Given that we already implement our own integrity mechanism, I wonder if we could/should just switch that particular checksum option off... :thinking:

**Comment by io7m** [comment]
This should be fixed in `1.1.4` (due out in the next day or so).
